ObjektGroesse("Wand",1024,600)
ObjektFarbe("Wand","orange")
Rechteck("Wilkommen")
ObjektFarbe("Wilkommen","green")
ObjektGroesse("Wilkommen",620,100)
Schrift("Wilkommen","Die Community")
SchriftGroesse("Wilkommen",90)
Rechteck("log")
ObjektPosition("log",0,535)
ObjektGroesse("log",290,53)
ObjektFarbe("log","black")
Schrift("log","Logout")
SchriftFarbe("log","red")
SchriftGroesse("log",45)
ObjektKlick("log",{Verweis("website.js")})
Rechteck("1n")
ObjektPosition("1n",0,130)
ObjektGroesse("1n",290,53)
ObjektFarbe("1n","red")
Schrift("1n","1.Nachricht")
SchriftArt("1n","Druckschrift")
SchriftGroesse("1n",46)
ObjektKlick("1n",{Abfrage("Willst du die nachricht lesen?",{Meldung("Hallo liebe leser heute gibts was zum lernen Eneuerbare-energien sind wichtig!Dadurch werden neue Menschen geboren.Diese haben spezziele Fähigkeiten(fliegen)!schrieb admin.")
},{Meldung("lies die nächste!")})})
Rechteck("2n")
ObjektPosition("2n",0,190)
ObjektGroesse("2n",290,53)
ObjektFarbe("2n","red")
Schrift("2n","2.Nachricht")
SchriftArt("2n","Druckschrift")
SchriftGroesse("2n",46)
ObjektKlick("2n",{Abfrage("Willst du die nachricht lesen?",{Meldung("Hey! wenn ihr Langeweile habt besucht mich auf Youtube unter Cd mick schrieb admin")
},{Meldung("lies die nächste!")})})
Rechteck("3n")
ObjektPosition("3n",0,250)
ObjektGroesse("3n",290,53)
ObjektFarbe("3n","red")
Schrift("3n","3.Nachricht")
SchriftArt("3n","Druckschrift")
SchriftGroesse("3n",46)
ObjektKlick("3n",{Abfrage("Willst du die nachricht lesen?",{Meldung("Sucht mal im Internet nach:Cortys schrieb admin")
},{Meldung("lies die nächste!")})})
Rechteck("4n")
ObjektPosition("4n",0,310)
ObjektGroesse("4n",290,53)
ObjektFarbe("4n","red")
Schrift("4n","4.Nachricht")
SchriftArt("4n","Druckschrift")
SchriftGroesse("4n",46)
ObjektKlick("4n",{Abfrage("Willst du die nachricht lesen?",{Meldung("Guckt euch auf You Tube Horrorschwein an schrieb admin")
},{Meldung("lies die nächste!")})})
Rechteck("ga")
ObjektPosition("ga",0,370)
ObjektGroesse("ga",290,53)
ObjektFarbe("ga","red")
Schrift("ga","Game List")
SchriftArt("ga","Druckschrift")
SchriftGroesse("ga",46)
ObjektKlick("ga",{Verweis("Gamelist.js")
})
Bild("Bild")
ObjektGroesse("Bild",404,600)
ObjektPosition("Bild",620,0)
ObjektQuelle("Bild","Carl.JPG")

