ObjektGroesse("Wand",1024,600)
Meldung("Wilkommen bei fahr das Auto.Das Spiel ist ganz einfach,nähmlich nur klicken")
Rechteck("Auto")
ObjektGroesse("Auto",300,150)
ObjektFarbe("Auto","red")
ObjektGruppe("Auto","Bus")
Rechteck("fenster")
ObjektGroesse("fenster",50,50)
ObjektPosition("fenster",230,15)
ObjektFarbe("fenster","white")
ObjektGruppe("fenster","Bus")
Rechteck("fenster2")
ObjektGroesse("fenster2",50,50)
ObjektPosition("fenster2",150,15)
ObjektFarbe("fenster2","white")
ObjektGruppe("fenster2","Bus")
Rechteck("fenster3")
ObjektGroesse("fenster3",50,50)
ObjektPosition("fenster3",70,15)
ObjektFarbe("fenster3","white")
ObjektGruppe("fenster3","Bus")
Rechteck("fenster4")
ObjektGroesse("fenster4",50,50)
ObjektPosition("fenster4",0,15)
ObjektFarbe("fenster4","white")
ObjektGruppe("fenster4","Bus")
Kreis("rei1")
ObjektPosition("rei1",240,141)
ObjektGroesse("rei1",70,70)
ObjektGruppe("rei1","Bus")
Kreis("rei2")
ObjektPosition("rei2",0,141)
ObjektGroesse("rei2",70,70)
ObjektGruppe("rei2","Bus")
ObjektKlick("Bus",{
	Abfrage("Willst du starten?",{
		ObjektBewegen("Bus",4,1024,0)
	},{
		Meldung("Oh,oh der Sprit ist leer")
	})
})
Rechteck("log")
ObjektPosition("log",0,535)
ObjektGroesse("log",290,53)
ObjektFarbe("log","black")
Schrift("log","Community")
SchriftFarbe("log","red")
SchriftGroesse("log",45)
ObjektKlick("log",{Verweis("Comunity.js")})




