ObjektGroesse("Wand",1024,600)
ObjektFarbe("Wand","grey")
Rechteck("admin")
ObjektGroesse("admin",1024,60)
ObjektFarbe("admin","red")
Schrift("admin","Programierer:Carl Damke")
SchriftGroesse("admin",50)
Rechteck("jah")
ObjektGroesse("jah",1024,60)
ObjektFarbe("jah","red")
ObjektPosition("jah",0,70)
Schrift("jah","Jahr:2014")
SchriftGroesse("jah",50)
Rechteck("ver")
ObjektGroesse("ver",1024,60)
ObjektFarbe("ver","red")
ObjektPosition("ver",0,140)
Schrift("ver","Version:2.0")
SchriftGroesse("ver",50)
ObjektKlick("ver",{Meldung("Version ist auf dem neusten Stand.")})
Rechteck("dan")
ObjektGroesse("dan",1024,60)
ObjektFarbe("dan","red")
ObjektPosition("dan",0,210)
Schrift("dan","Weiteren Dank an:Clemens&Clara Damke")
SchriftGroesse("dan",50)
Rechteck("sra")
ObjektGroesse("sra",1024,60)
ObjektFarbe("sra","red")
ObjektPosition("sra",0,280)
Schrift("sra","Programiersprache:jAnimation 2.2")
SchriftGroesse("sra",50)
ObjektKlick("sra",{Internet("http://www.la-mann.com/")})
Rechteck("log")
ObjektPosition("log",0,550)
ObjektGroesse("log",290,53)
ObjektFarbe("log","black")
Schrift("log","Zurück")
SchriftFarbe("log","red")
SchriftGroesse("log",45)
ObjektKlick("log",{Verweis("project.js")})








