ObjektGroesse("Wand",1024,600)
ObjektFarbe("Wand","black")
Rechteck("carldamke")
ObjektFarbe("carldamke","black")
ObjektGroesse("carldamke",300,100)
ObjektPosition("carldamke",310,0)
Schrift("carldamke","Carl Damke")
SchriftGroesse("carldamke",50)
SchriftFarbe("carldamke","red")
ObjektKlick("carldamke",{
	Eingabe("User:Admin","",{
		Wenn(Wert gleich "leelp",{
			Verweis("home.js")
		},{
			Meldung("falsch!")
		})
	})
},{})
Rechteck("weit")
ObjektFarbe("weit","blue")
ObjektGroesse("weit",150,53)
ObjektPosition("weit",890,550)
ObjektKlick("weit",{
	Verweis("weitere.js")
})
Schrift("weit","Über")
SchriftGroesse("weit",53)
SchriftFarbe("weit","white")
Rechteck("s1")
ObjektFarbe("s1","blue")
ObjektGroesse("s1",10,600)
Rechteck("s2")
ObjektFarbe("s2","blue")
ObjektGroesse("s2",10,600)
ObjektPosition("s2",1015,0)
Rechteck("p1")
ObjektFarbe("p1","red")
ObjektGroesse("p1",300,50)
ObjektPosition("p1",300,150)
Schrift("p1","23.1.2014")
SchriftGroesse("p1",50)
ObjektKlick("p1",{Meldung("Dies ist meine neue Website.Als Ersatz von:http://carl.la-mann.com")})
Rechteck("p2")
ObjektFarbe("p2","red")
ObjektGroesse("p2",300,50)
ObjektPosition("p2",300,200)
Schrift("p2","22.1.2014")
SchriftGroesse("p2",50)
ObjektKlick("p2",{Meldung("Hallo Freunde.Seit Heute Programmiere ich an der neuen Website:)")})
Rechteck("p3")
ObjektFarbe("p3","red")
ObjektGroesse("p3",300,50)
ObjektPosition("p3",300,250)
Schrift("p3","21.1.2014")
SchriftGroesse("p3",50)
ObjektKlick("p3",{Meldung("Hi ich bin Lee und für euch erstelle ich diese neue Website:-)")})
Rechteck("ga")
ObjektPosition("ga",0,0)
ObjektGroesse("ga",300,53)
ObjektFarbe("ga","blue")
Schrift("ga","Meine Werke")
SchriftArt("ga","Druckschrift")
SchriftGroesse("ga",46)
ObjektKlick("ga",{Verweis("Gamelist.js")
})
Rechteck("ti")
ObjektFarbe("ti","grey")
ObjektGroesse("ti",290,50)
ObjektPosition("ti",665,0)
Schrift("ti","9.5.2014")
SchriftGroesse("ti",50)


