ObjektGroesse("Wand",1024,600)
//"carldamke"=titelbox
Rechteck("carldamke")
ObjektFarbe("carldamke","orange")
ObjektGroesse("carldamke",400,70)
ObjektFarbe("Wand","blue")
Schrift("carldamke","Carl Damke")
SchriftGroesse("carldamke",70)
Rechteck("info")
ObjektPosition("info",0,150)
ObjektGroesse("info",200,120)
ObjektFarbe("info","blue")
Schrift("info","Info:")
SchriftGroesse("info",70)
SchriftFarbe("info","white")
Rechteck("email")
ObjektPosition("email",0,230)
ObjektGroesse("email",290,53)
ObjektFarbe("email","blue")
Schrift("email","Email:carl@cortys.de")
SchriftGroesse("email",30)
SchriftFarbe("email","white")
Rechteck("telefon")
ObjektPosition("telefon",0,270)
ObjektGroesse("telefon",290,53)
ObjektFarbe("telefon","blue")
Schrift("telefon","Tel/05251 8782954")
SchriftGroesse("telefon",30)
SchriftFarbe("telefon","white")
Rechteck("com")
ObjektPosition("com",800,0)
ObjektGroesse("com",290,53)
ObjektFarbe("com","blue")
Schrift("com","Community")
SchriftArt("com","Druckschrift")
SchriftFarbe("com","white")
SchriftGroesse("com",39)
Rechteck("da")
ObjektPosition("da",800,60)
ObjektGroesse("da",290,27)
ObjektFarbe("da","blue")
Schrift("da","Anmelden/Reg.")
SchriftGroesse("da",27)
SchriftFarbe("da","white")
ObjektKlick("da",{Abfrage("Willst du in die Community?",{Meldung("Hallo")
Verweis("Comunity.js")},{Meldung("Bis zum nächsten mal")})})
Rechteck("weit")
ObjektFarbe("weit","blue")
ObjektGroesse("weit",290,53)
ObjektPosition("weit",750,270)
ObjektKlick("weit",{Verweis("weitere.js")})
Schrift("weit","Mehr Infos")
SchriftGroesse("weit",53)
SchriftFarbe("weit","white")
//"strip1"=weißer streifen1
Rechteck("strip1")
ObjektGroesse("strip1",10,600)


